In [1]:
import pandas as pd
import sys
#sys.path.insert(0, '/Users/eduardomorenoortiz/Desktop/ITAM/nanook/nlp_nanook/src/') # LOCAL
sys.path.insert(0, r'C:\Users\eduardo.moreno\OneDrive - NEORIS\Desktop\courses\nlp\nlp_nanook\src') # Windows
from utils.utils import remove_stop_words_from_dataframe

# Read and preprocess data

In [2]:
df_stemm_lemm = pd.read_pickle(r'..\..\..\data\preprocessed\stemm_lemm_text_fb_pages_nanook.pkl')

In [3]:
df_select = df_stemm_lemm[
    [
        'Facebook Id', 'Post Created', 
        'Total Interactions', 'Likes', 'Comments', 'Shares', 'Love', 'Wow', 'Haha', 'Sad', 'Angry', 'Care', 
        'Message', 'Message_clean', 'Message_clean_stemm', 'Message_clean_lemm',
        ]
    ]
df_select.head(1)

,Facebook Id,Post Created,Total Interactions,Likes,Comments,Shares,Love,Wow,Haha,Sad,Angry,Care,Message,Message_clean,Message_clean_stemm,Message_clean_lemm
0,97984508920,2014-12-31 23:29:00 CST,13,9,2,2,0,0,0,0,0,0,Energía #nuclear es buena y clave para la solu...,energia nuclear es buena y clave para la soluc...,energi nucl es buen y clav par la solucion al ...,energia nuclear ser buen y clave para el soluc...

Remove stop words from messages

In [4]:
df_clean = remove_stop_words_from_dataframe(
    df=df_select, 
    columns=["Message", "Message_clean", "Message_clean_stemm", "Message_clean_lemm"], 
    stop_words_file=r"..\..\utils\spanish_stopwords.txt"
    )

C:\Users\eduardo.moreno\OneDrive - NEORIS\Desktop\courses\nlp\nlp_nanook\src\utils\utils.py:146: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df[column + '_stpWrd'] = aux
C:\Users\eduardo.moreno\OneDrive - NEORIS\Desktop\courses\nlp\nlp_nanook\src\utils\utils.py:146: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df[column + '_stpWrd'] = aux
C:\Users\eduardo.moreno\OneDrive - NEORIS\Desktop\courses\nlp\nlp_nanook\src\utils\utils.py:146: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df[column + '_stpWrd'] = aux
C:\Users\eduardo.moreno\OneDrive - NEORIS\Desktop\courses\nlp\nlp_nanook\src\utils\utils.py:146: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df[column + '_stpWrd'] = aux

In [5]:
df_clean[
    [
        'Message_clean', 'Message_clean_stpWrd',
        'Message_clean_stemm', 'Message_clean_stemm_stpWrd',
        'Message_clean_lemm', 'Message_clean_lemm_stpWrd'
        ]].head(1)

,Message_clean,Message_clean_stpWrd,Message_clean_stemm,Message_clean_stemm_stpWrd,Message_clean_lemm,Message_clean_lemm_stpWrd
0,energia nuclear es buena y clave para la soluc...,energia nuclear clave solucion cambio climatico,energi nucl es buen y clav par la solucion al ...,energi nucl clav par solucion cambi climat,energia nuclear ser buen y clave para el soluc...,energia nuclear clave solucion cambio climatico

Save final dataframe

In [6]:
df_clean[['Facebook Id', 'Post Created', 'Total Interactions', 'Likes',
       'Comments', 'Shares', 'Love', 'Wow', 'Haha', 'Sad', 'Angry', 'Care',
       'Message_stpWrd', 'Message_clean_stpWrd', 'Message_clean_stemm_stpWrd',
       'Message_clean_lemm_stpWrd']].to_pickle(r"..\..\..\data\preprocessed\stemm_lemm_stop_words_stop_fb_pages.pkl")