# Load data

In [1]:
import pandas as pd

In [2]:
selected_data = pd.read_pickle(r"..\..\..\data\preprocessed\full_data_organizations.pkl")

# Hugging Face (*Transformers*)

In [3]:
from transformers import pipeline, BertTokenizer

Import model

In [4]:
distilled_student_sentiment_classifier = pipeline(
    model="lxyuan/distilbert-base-multilingual-cased-sentiments-student", 
    return_all_scores=True
)

c:\Users\eduardo.moreno\AppData\Local\anaconda3\envs\env_nlp\Lib\site-packages\transformers\pipelines\text_classification.py:104: UserWarning: `return_all_scores` is now deprecated,  if want a similar functionality use `top_k=None` instead of `return_all_scores=True` or `top_k=1` instead of `return_all_scores=False`.
  warnings.warn(

Import tokenizer

In [5]:
tokenizer = BertTokenizer.from_pretrained('lxyuan/distilbert-base-multilingual-cased-sentiments-student')

The tokenizer class you load from this checkpoint is not the same type as the class this function is called from. It may result in unexpected tokenization.
The tokenizer class you load from this checkpoint is 'DistilBertTokenizer'.
The class this function is called from is 'BertTokenizer'.

Example of use and response of the model

In [6]:
distilled_student_sentiment_classifier("I love this movie and i would watch it again and again!")

[[{'label': 'positive', 'score': 0.9731044769287109},
  {'label': 'neutral', 'score': 0.016910076141357422},
  {'label': 'negative', 'score': 0.009985473938286304}]]

Let's use it with our data

In [7]:
print(selected_data.iloc[418233]['Message'])

Al celebrarse hoy, 5 de junio, el Día Mundial del Medio Ambiente desde el 1954 el Ministerio de Defensa, sus instituciones y dependencias, reafirma su apoyo incondicional a la conservación del medio ambiente en toda su área de responsabilidad en el territorio de la República Dominicana, sus espacios terrestres, marítimos y aéreos. El MIDE se une hoy al Ministerio de Medio Ambiente y Recursos Naturales, razón por la cual seguimos realizando operaciones en todo el territorio nacional para proteger todos los ecosistemas dominicanos. Luchamos contra la tala de árboles para conservar las cuencas acuíferas e hidrográficas que dan origen a los ríos y arroyos que proveen al pueblo dominicano del preciado liquido, como es agua potable. De igualmente manera, ante los retos que nos impone el cambio climático, dentro de nuestra planificación estratégica está concebida la conservación de energía así como el fomento para el uso de fuentes alternativas como la energía solar. El Día Mundial del Medio Ambiente es un vínculo por medio del cual la Organización de Naciones Unidas (ONU) sensibiliza a la población del mundo en relación con temas ambientales, llamando la atención sobre la necesidad de proteger y conservar los recursos naturales como forma de conservar la vida del planeta y los ciudadanos.

In [8]:
distilled_student_sentiment_classifier(selected_data.iloc[418233]['Message'])

[[{'label': 'positive', 'score': 0.6169759035110474},
  {'label': 'neutral', 'score': 0.07673612982034683},
  {'label': 'negative', 'score': 0.3062879145145416}]]

`distilbert-base-multilingual-cased-sentiments-student` as it base model `bert` accepts only $512$ tokens, so what do you think will happen if we try to analyze an input **greater than 512 tokens**?

In [9]:
txt = selected_data['Message'][0]
print(txt)

A LOS NACIDOS ENTRE 1970 Y 1987 Somos una generación especial y nos denominaron la generación X y como no, si nuestra infancia estuvo llena de cambios Somos la última generación que jugaba en la calle y en los recreos del colegio a las bolitas, a el escondite, somos la primera generación que jugó con videojuegos, fuimos a parques de atracciones y vimos caricaturas a color. Fuimos los últimos en grabar canciones de la radio en casettes (como olvidarlo si mientras se grababa en algunos casos no podíamos ni hablar) y vimos películas en versión Beta y VHS PERO orgullosos pioneros del personal stereo y los CD's. Cuantos no tuvimos que tragarnos, Salvado por la Campana (con todo y Screech), Beverly Hills 90210. Nosotros vimos la caída de torres gemelas y también vimos caer el muro de Berlín. Aprendimos a utilizar los ordenadores antes que nuestros padres y abuelos, y sobre todo antes de todos esos niños cerebritos de hoy en día y nunca vimos a los que no sabían usar los ordenadores como una especie de "retardados" como sucede hoy. Jugamos con el Double Dragon, Street Fighter, empezamos el Mortal Kombat, el tetris, el Mario Bross, nos pegábamos a la tele a mirar Hugo y como otros jugaban desde sus casas usando el teléfono de red fija!! vimos los anuncios de los primeros celulares (que parecían ladrillos) y creímos que Internet sería un mundo libre. Somos la Generación de Xuxa, Robotech, Gi Joe, Los Halcones Galácticos, los ThunderCats, los Transformers, He-Man y las Tortugas Ninja, Del Correcaminos, Los Supercampeones, Espartaco, Mazinger, de los Pitufos, La Pantera Rosa, Los Picapiedras, El pájaro loco, Candi Candi, Remi y Marco. Los que crecieron escuchando a Madonna, Michael Jackson y Guns N'Roses, New Kids on the block, Por supuesto en ver y vivir los primeros VIDEOS MUSICALES , Los Locomía y sus abanicos. La última generación de las botellas de litro de Coca-Cola familiar cuando un litro alcanzaba para toda la familia!! Y los últimos en ser mandados a comprar en la bolsa de cuadritos. Este correo está dedicado a las personas que nacieron entre 1970 y 1987. La verdad es que no sé cómo hemos sobrevivido!!!! Mirando atrás es difícil creer que estemos vivos: viajábamos en autos sin cinturones de seguridad traseros, sin sillitas especiales y sin air-bag, hacíamos viajes de 10-12h y no sufríamos el síndrome de la clase turista. No tuvimos puertas con protecciones, armarios o frascos de medicinas con tapa a prueba de niños. Andábamos en bicicleta o patines sin casco, ni protectores para rodillas y codos. Los columpios eran de metal y resbaladilla y con esquinas en punta oxidada . No había celulares!!!!. Íbamos a clase cargados de libros y cuadernos, todo metido en una mochila o bolsón que rara vez tenía refuerzo para los hombros y mucho menos, ruedas!! Cuantos no recogimos del suelo nuestros útiles al romperse la mochila! Y el que tenia un pantalón marca Wrangler. No tuvimos PlayStation, no había 99 canales de televisión, pantallas planas, sonido surround, mp3s, ipods, computadores e Internet, pero nos lo pasábamos de lo lindo tirándonos globos con agua, o jugando con los playmobil. Y nunca escuchamos sobre el calentamiento global. No era necesario tener fotoblog, Hi5 o MySpace, Facebook, twitter, para saber si existíamos, bastaba con hacer bien fuerte la "silvada" del grupo o gritar fuera de la casa, en plena calle, para que toda la cuadra saliera de sus casas. Éramos el zanahoria, la china, la flaca, la pecosa, el negro, el chato o cosas así, pero todos pertenecíamos al mismo grupo y por el apodo sabíamos de inmediato quien era (ahora serian zanahoriitax, shiina, flahkah, p'kosiita, neghhro y shatto). jjajajaja Éramos responsables de nuestras acciones y acarreábamos con las consecuencias, no había nadie para resolver eso. Tuvimos libertad, fracaso, éxito y responsabilidad, y aprendimos a crecer con todo ello. ¡FELICIDADES! Sobrevivimos a un mega cambio, ahora si tienes hijos, piensa por que no lo dejas hacer esas cosas si lo pasaste tan bien? Pasa esto a otros que tuvieron la suerte de crecer como niños, recordemos lo bueno de la vida. Lo fácil que es ser felices, la grandeza de lo sencillo. No necesitamos todas esas etiquetas, todas esas superficialidades, cosas, móviles, ropa... recordemos cómo ser niños, pero sobre todo, cómo ser libres!! Por: Luis Sosa

In [10]:
tokens = tokenizer.encode_plus(txt, add_special_tokens=False)

len(tokens['input_ids'])

Token indices sequence length is longer than the specified maximum sequence length for this model (1201 > 512). Running this sequence through the model will result in indexing errors

1201

In [11]:
tokens = tokenizer.encode_plus(txt, add_special_tokens=False,
                               return_tensors='pt')

print(len(tokens['input_ids'][0]))
tokens

1201

{'input_ids': tensor([[  138,   149, 21793,  ..., 12816, 12882, 10466]]), 'token_type_ids': tensor([[0, 0, 0,  ..., 0, 0, 0]]), 'attention_mask': tensor([[1, 1, 1,  ..., 1, 1, 1]])}

Here we have specified a few arguments that require some explanation.

* `max_length` - this tell the tokenizer the maximum number of tokens we want to see in each sample, for BERT we almost always use `512` as that is the length of sequences that BERT consumes.

* `truncation` - if our input string `txt` contains more tokens than allowed (specified in `max_length` parameter) then we cut all tokens past the `max_length` limit.

* `padding` - if our input string `txt` contains less tokens than specified by `max_length` then we pad the sequence with zeros (`0` is the token ID for *'[PAD]'* - BERTs padding token).

* `add_special_tokens` - whether or not to add special tokens, when using BERT we always want this to be `True` unless we are adding them ourselves.

| Token | ID | Description |
| --- | --- | --- |
| [PAD] | 0 | Used to fill empty space when input sequence is shorter than required sequence size for model |
| [UNK] | 100 | If a word/character is not found in BERTs vocabulary it will be represented by this *unknown* token |
| [CLS] | 101 | Represents the start of a sequence |
| [SEP] | 102 | Seperator token to denote the end of a sequence and as a seperator where there are multiple sequences |
| [MASK] | 103 | Token used for masking other tokens, used for masked language modeling |

*Note that our tokenized sequence begins with `101`, the seperator token `102` can be found seperating the input sequence and padding tokens `0`.*

* `return_tensors` - here we specify either `'pt'` to return PyTorch tensors, or `'tf'` to return TensorFlow tensors.

In [12]:
try:
    response = distilled_student_sentiment_classifier(txt)
    print(response)
except Exception as e:
    print(f"Something went WRONG: {e}")

Token indices sequence length is longer than the specified maximum sequence length for this model (1203 > 512). Running this sequence through the model will result in indexing errors

Something went WRONG: The size of tensor a (1203) must match the size of tensor b (512) at non-singleton dimension 1

What happen if we only send a chunk of the post?

In [13]:
try:
    response = distilled_student_sentiment_classifier(txt[:1500])
    print(response)
except Exception as e:
    print(f"Something went WRONG: {e}")

[[{'label': 'positive', 'score': 0.28041714429855347}, {'label': 'neutral', 'score': 0.1233644187450409}, {'label': 'negative', 'score': 0.5962184071540833}]]

We will use [LangChain](https://python.langchain.com/v0.2/docs/introduction/) to split posts so we can compute the sentiment of each split.

In [14]:
from langchain_text_splitters import RecursiveCharacterTextSplitter

In [15]:
text_splitter = RecursiveCharacterTextSplitter(
    chunk_size=700,  # Ajusta según sea necesario
    chunk_overlap=50,
    separators=[" "]
)

In [16]:
texts = text_splitter.create_documents([txt])
print(len(texts))

7

In [17]:
len(texts[0].page_content)

693

In [18]:
texts[0].page_content[:100]

'A LOS NACIDOS ENTRE 1970 Y 1987 Somos una generación especial y nos denominaron la generación X y co'

In [19]:
texts[0].page_content[-115:]

"eros del personal stereo y los CD's. Cuantos no tuvimos que tragarnos, Salvado por la Campana (con todo y Screech),"

In [20]:
texts[1].page_content[100:]

'gemelas y también vimos caer el muro de Berlín. Aprendimos a utilizar los ordenadores antes que nuestros padres y abuelos, y sobre todo antes de todos esos niños cerebritos de hoy en día y nunca vimos a los que no sabían usar los ordenadores como una especie de "retardados" como sucede hoy. Jugamos con el Double Dragon, Street Fighter, empezamos el Mortal Kombat, el tetris, el Mario Bross, nos pegábamos a la tele a mirar Hugo y como otros jugaban desde sus casas usando el teléfono de red fija!! vimos los anuncios de los primeros celulares (que parecían ladrillos) y creímos que Internet sería'

In [21]:
pos_sent = []
neu_sent = []
neg_sent = []

for text_i in texts:
    response = distilled_student_sentiment_classifier(text_i.page_content)

    print(text_i.page_content)
    print(response, '\n')

    for sent in response[0]:
        if sent['label'] == 'positive':
            pos_sent.append(sent['score'])
        elif sent['label'] == 'neutral':
            neu_sent.append(sent['score'])
        elif sent['label'] == 'negative':
            neg_sent.append(sent['score'])

A LOS NACIDOS ENTRE 1970 Y 1987 Somos una generación especial y nos denominaron la generación X y como no, si nuestra infancia estuvo llena de cambios Somos la última generación que jugaba en la calle y en los recreos del colegio a las bolitas, a el escondite, somos la primera generación que jugó con videojuegos, fuimos a parques de atracciones y vimos caricaturas a color. Fuimos los últimos en grabar canciones de la radio en casettes (como olvidarlo si mientras se grababa en algunos casos no podíamos ni hablar) y vimos películas en versión Beta y VHS PERO orgullosos pioneros del personal stereo y los CD's. Cuantos no tuvimos que tragarnos, Salvado por la Campana (con todo y Screech),
[[{'label': 'positive', 'score': 0.45823341608047485}, {'label': 'neutral', 'score': 0.15719184279441833}, {'label': 'negative', 'score': 0.3845748007297516}]]

Salvado por la Campana (con todo y Screech), Beverly Hills 90210. Nosotros vimos la caída de torres gemelas y también vimos caer el muro de Berlín. Aprendimos a utilizar los ordenadores antes que nuestros padres y abuelos, y sobre todo antes de todos esos niños cerebritos de hoy en día y nunca vimos a los que no sabían usar los ordenadores como una especie de "retardados" como sucede hoy. Jugamos con el Double Dragon, Street Fighter, empezamos el Mortal Kombat, el tetris, el Mario Bross, nos pegábamos a la tele a mirar Hugo y como otros jugaban desde sus casas usando el teléfono de red fija!! vimos los anuncios de los primeros celulares (que parecían ladrillos) y creímos que Internet sería
[[{'label': 'positive', 'score': 0.14619667828083038}, {'label': 'neutral', 'score': 0.1138191893696785}, {'label': 'negative', 'score': 0.7399840950965881}]]

parecían ladrillos) y creímos que Internet sería un mundo libre. Somos la Generación de Xuxa, Robotech, Gi Joe, Los Halcones Galácticos, los ThunderCats, los Transformers, He-Man y las Tortugas Ninja, Del Correcaminos, Los Supercampeones, Espartaco, Mazinger, de los Pitufos, La Pantera Rosa, Los Picapiedras, El pájaro loco, Candi Candi, Remi y Marco. Los que crecieron escuchando a Madonna, Michael Jackson y Guns N'Roses, New Kids on the block, Por supuesto en ver y vivir los primeros VIDEOS MUSICALES , Los Locomía y sus abanicos. La última generación de las botellas de litro de Coca-Cola familiar cuando un litro alcanzaba para toda la familia!! Y los últimos en ser mandados a comprar en la
[[{'label': 'positive', 'score': 0.7550170421600342}, {'label': 'neutral', 'score': 0.07655859738588333}, {'label': 'negative', 'score': 0.16842439770698547}]]

Y los últimos en ser mandados a comprar en la bolsa de cuadritos. Este correo está dedicado a las personas que nacieron entre 1970 y 1987. La verdad es que no sé cómo hemos sobrevivido!!!! Mirando atrás es difícil creer que estemos vivos: viajábamos en autos sin cinturones de seguridad traseros, sin sillitas especiales y sin air-bag, hacíamos viajes de 10-12h y no sufríamos el síndrome de la clase turista. No tuvimos puertas con protecciones, armarios o frascos de medicinas con tapa a prueba de niños. Andábamos en bicicleta o patines sin casco, ni protectores para rodillas y codos. Los columpios eran de metal y resbaladilla y con esquinas en punta oxidada . No había celulares!!!!. Íbamos a
[[{'label': 'positive', 'score': 0.1800335794687271}, {'label': 'neutral', 'score': 0.33465394377708435}, {'label': 'negative', 'score': 0.4853125512599945}]]

punta oxidada . No había celulares!!!!. Íbamos a clase cargados de libros y cuadernos, todo metido en una mochila o bolsón que rara vez tenía refuerzo para los hombros y mucho menos, ruedas!! Cuantos no recogimos del suelo nuestros útiles al romperse la mochila! Y el que tenia un pantalón marca Wrangler. No tuvimos PlayStation, no había 99 canales de televisión, pantallas planas, sonido surround, mp3s, ipods, computadores e Internet, pero nos lo pasábamos de lo lindo tirándonos globos con agua, o jugando con los playmobil. Y nunca escuchamos sobre el calentamiento global. No era necesario tener fotoblog, Hi5 o MySpace, Facebook, twitter, para saber si existíamos, bastaba con hacer bien
[[{'label': 'positive', 'score': 0.13677650690078735}, {'label': 'neutral', 'score': 0.21207258105278015}, {'label': 'negative', 'score': 0.6511509418487549}]]

para saber si existíamos, bastaba con hacer bien fuerte la "silvada" del grupo o gritar fuera de la casa, en plena calle, para que toda la cuadra saliera de sus casas. Éramos el zanahoria, la china, la flaca, la pecosa, el negro, el chato o cosas así, pero todos pertenecíamos al mismo grupo y por el apodo sabíamos de inmediato quien era (ahora serian zanahoriitax, shiina, flahkah, p'kosiita, neghhro y shatto). jjajajaja Éramos responsables de nuestras acciones y acarreábamos con las consecuencias, no había nadie para resolver eso. Tuvimos libertad, fracaso, éxito y responsabilidad, y aprendimos a crecer con todo ello. ¡FELICIDADES! Sobrevivimos a un mega cambio, ahora si tienes hijos,
[[{'label': 'positive', 'score': 0.3593401312828064}, {'label': 'neutral', 'score': 0.058374736458063126}, {'label': 'negative', 'score': 0.5822851061820984}]]

a un mega cambio, ahora si tienes hijos, piensa por que no lo dejas hacer esas cosas si lo pasaste tan bien? Pasa esto a otros que tuvieron la suerte de crecer como niños, recordemos lo bueno de la vida. Lo fácil que es ser felices, la grandeza de lo sencillo. No necesitamos todas esas etiquetas, todas esas superficialidades, cosas, móviles, ropa... recordemos cómo ser niños, pero sobre todo, cómo ser libres!! Por: Luis Sosa
[[{'label': 'positive', 'score': 0.8178251385688782}, {'label': 'neutral', 'score': 0.08240234106779099}, {'label': 'negative', 'score': 0.09977256506681442}]]

For the final output we will compute the average of sentiment on each partition and will return the highest as the final sentiment of the initial post.

In [22]:
import numpy  as np

In [23]:
mean_scores = [np.mean(pos_sent), np.mean(neu_sent), np.mean(neg_sent)]

In [24]:
mean_scores

[0.4076317846775055, 0.14786760455795697, 0.44450063684156965]

In [25]:
sentiment = np.argmax(mean_scores)
score = np.max(mean_scores)

if sentiment == 0:
    print(f"The sentiment of the post is POSITIVE: {score}")
if sentiment == 1:
    print(f"The sentiment of the post is NEUTRAL: {score}")
if sentiment == 2:
    print(f"The sentiment of the post is NEGATIVE: {score}")

The sentiment of the post is NEGATIVE: 0.44450063684156965

Now let's compute the sentiment for each post!

In [26]:
from tqdm import tqdm

In [27]:
def get_sentiment(post):
    try:
        response = distilled_student_sentiment_classifier(post)
        pos_sent = []
        neu_sent = []
        neg_sent = []
        for sent in response[0]:
            if sent['label'] == 'positive':
                pos_sent.append(sent['score'])
            elif sent['label'] == 'neutral':
                neu_sent.append(sent['score'])
            elif sent['label'] == 'negative':
                neg_sent.append(sent['score'])
        mean_scores = [np.mean(pos_sent), np.mean(neu_sent), np.mean(neg_sent)]
        sentiment = np.argmax(mean_scores)
        score = np.max(mean_scores)
        if sentiment == 0:
            sentiment = 'Positive'
        elif sentiment == 1:
            sentiment = 'Neutral'
        else:
            sentiment = 'Negative'

    #except Exception as e:
    except BaseException as e:
        # Split the post
        texts = text_splitter.create_documents([post])
        # Compute the sentiment for each split
        pos_sent = []
        neu_sent = []
        neg_sent = []
        for text_i in texts:
            response = distilled_student_sentiment_classifier(text_i.page_content)
            # Compute avg sentiment
            for sent in response[0]:
                if sent['label'] == 'positive':
                    pos_sent.append(sent['score'])
                elif sent['label'] == 'neutral':
                    neu_sent.append(sent['score'])
                elif sent['label'] == 'negative':
                    neg_sent.append(sent['score'])
        # Compute final sentiment and score
        mean_scores = [np.mean(pos_sent), np.mean(neu_sent), np.mean(neg_sent)]
        sentiment = np.argmax(mean_scores)
        score = np.max(mean_scores)
        if sentiment == 0:
            sentiment = 'Positive'
        elif sentiment == 1:
            sentiment = 'Neutral'
        else:
            sentiment = 'Negative'
    
    return {'sentiment': sentiment, 'score': score}

In [28]:
def get_sentiment(post):

    tokens = distilled_student_sentiment_classifier.tokenizer(post, return_tensors='pt', truncation=False)['input_ids']

    if tokens.size(1) < 512:
        response = distilled_student_sentiment_classifier(post)
        pos_sent = []
        neu_sent = []
        neg_sent = []
        for sent in response[0]:
            if sent['label'] == 'positive':
                pos_sent.append(sent['score'])
            elif sent['label'] == 'neutral':
                neu_sent.append(sent['score'])
            elif sent['label'] == 'negative':
                neg_sent.append(sent['score'])
        mean_scores = [np.mean(pos_sent), np.mean(neu_sent), np.mean(neg_sent)]
        sentiment = np.argmax(mean_scores)
        score = np.max(mean_scores)
        if sentiment == 0:
            sentiment = 'Positive'
        elif sentiment == 1:
            sentiment = 'Neutral'
        else:
            sentiment = 'Negative'

    else:
        # Split the post
        texts = text_splitter.create_documents([post])
        # Compute the sentiment for each split
        pos_sent = []
        neu_sent = []
        neg_sent = []
        for text_i in texts:
            response = distilled_student_sentiment_classifier(text_i.page_content)
            # Compute avg sentiment
            for sent in response[0]:
                if sent['label'] == 'positive':
                    pos_sent.append(sent['score'])
                elif sent['label'] == 'neutral':
                    neu_sent.append(sent['score'])
                elif sent['label'] == 'negative':
                    neg_sent.append(sent['score'])
        # Compute final sentiment and score
        mean_scores = [np.mean(pos_sent), np.mean(neu_sent), np.mean(neg_sent)]
        sentiment = np.argmax(mean_scores)
        score = np.max(mean_scores)
        if sentiment == 0:
            sentiment = 'Positive'
        elif sentiment == 1:
            sentiment = 'Neutral'
        else:
            sentiment = 'Negative'
    
    return {'sentiment': sentiment, 'score': score}

We will select a sample from all data and compute the sentiment for those posts.

In [29]:
import random
from random import sample, seed

In [30]:
seed(42)
sub_sample = selected_data.loc[sample(selected_data.index.to_list(), int(len(selected_data.index.to_list())*0.1))]

Aditionally we will remove URLs from all posts

In [31]:
import re

In [32]:
def remove_urls(text):
    # Expresión regular para encontrar URLs
    url_pattern = re.compile(r'https?://\S+|www\.\S+')
    # Reemplaza todas las URLs con una cadena vacía
    return url_pattern.sub('', text)

In [33]:
sub_sample['Message_clean'] = sub_sample['Message'].apply(lambda x: remove_urls(x))

In [34]:
sub_sample

,Message,Message_stpWrd,Message_clean_lemm_stpWrd,organizations,Message_clean
375233,PLAN DE EMERGENCIA Y CONTINGENCIA DISEÑADO POR...,PLAN EMERGENCIA CONTINGENCIA DISEÑADO ADMINIST...,plan emergencia contingencia disenado administ...,"[BOGOTÁ, Cambio Climático]",PLAN DE EMERGENCIA Y CONTINGENCIA DISEÑADO POR...
83975,un análisis breve sobre la #COP21,análisis breve #COP21,analisis breve cop21,[],un análisis breve sobre la #COP21
774421,RT. Un docena de manifestantes semidesnudos de...,RT. docena manifestantes semidesnudos movimien...,rt docena manifestante semidesnudo movimiento ...,"[RT, Parlamento británico]",RT. Un docena de manifestantes semidesnudos de...
699239,Agregó que también se darán a conocer las sanc...,darán sanciones cumplan reglamento.,agregar tambien sancion cumplir reglamento,[],Agregó que también se darán a conocer las sanc...
646095,⚠️ATENTO AVISO⚠️ Debido a varias afectaciones ...,⚠️ATENTO AVISO⚠️ afectaciones tormenta inverna...,atento aviso afectacion tormenta invernal ciud...,[COP 25 sobre Cambio Climático],⚠️ATENTO AVISO⚠️ Debido a varias afectaciones ...
...,...,...,...,...,...
299552,En Colombia se previenen todos los riesgos a l...,Colombia previenen riesgos salud cambio climát...,colombia prevenir riesgo salud cambio climatic...,[],En Colombia se previenen todos los riesgos a l...
1228502,🔵 Medidas del PPCV en el Debate de Política Ge...,🔵 Medidas PPCV Debate Política General. ✅ Plan...,medida ppcv debate politica general plan ppcv ...,"[PPCV, Cambio Climático #DebatCV]",🔵 Medidas del PPCV en el Debate de Política Ge...
623413,#GrandesLogros2019 | El estado de deterioro de...,#GrandesLogros2019 | deterioro planeta 🌎 movil...,grandeslogros2019 deterioro planeta movilizar ...,[],#GrandesLogros2019 | El estado de deterioro de...
405585,"#JPCCinforma Los movimientos NuestrasVoces, Gr...","#JPCCinforma movimientos NuestrasVoces, GreenF...",jpccinforma movimiento nuestrasvoz greenfaith ...,"[Consejo Episcopal Latinoamericano, Movimiento...","#JPCCinforma Los movimientos NuestrasVoces, Gr..."
1240328,Avances Informativos Viernes 09 de Septiembre ...,Avances Informativos Viernes 09 Septiembre 202...,avance informativo viernes 09 septiembre 2022 ...,[Avances Informativos Viernes 09 de Septiembre...,Avances Informativos Viernes 09 de Septiembre ...

In [35]:
list_msgs = sub_sample['Message_clean'].to_list()

Next cell took around **6 hours** to complete (please be patient)...

In [36]:
if 1 == 0:
    list_sentiment = []
    list_scores = []

    for post_i in tqdm(list_msgs):
        response = get_sentiment(post_i)
        list_sentiment.append(response['sentiment'])
        list_scores.append(response['score'])
    
    sub_sample['sentiment'] = list_sentiment
    sub_sample['score'] = list_scores

    sub_sample.to_pickle(r"..\..\..\data\preprocessed\sentiment_analysis_subsample.pkl")
else:
    sub_sample = pd.read_pickle(r"..\..\..\data\preprocessed\sentiment_analysis_subsample.pkl")

In [37]:
sub_sample.head()

,Message,Message_stpWrd,Message_clean_lemm_stpWrd,organizations,Message_clean,sentiment,score
375233,PLAN DE EMERGENCIA Y CONTINGENCIA DISEÑADO POR...,PLAN EMERGENCIA CONTINGENCIA DISEÑADO ADMINIST...,plan emergencia contingencia disenado administ...,"[BOGOTÁ, Cambio Climático]",PLAN DE EMERGENCIA Y CONTINGENCIA DISEÑADO POR...,Positive,0.681693
83975,un análisis breve sobre la #COP21,análisis breve #COP21,analisis breve cop21,[],un análisis breve sobre la #COP21,Positive,0.482537
774421,RT. Un docena de manifestantes semidesnudos de...,RT. docena manifestantes semidesnudos movimien...,rt docena manifestante semidesnudo movimiento ...,"[RT, Parlamento británico]",RT. Un docena de manifestantes semidesnudos de...,Negative,0.819510
699239,Agregó que también se darán a conocer las sanc...,darán sanciones cumplan reglamento.,agregar tambien sancion cumplir reglamento,[],Agregó que también se darán a conocer las sanc...,Negative,0.530870
646095,⚠️ATENTO AVISO⚠️ Debido a varias afectaciones ...,⚠️ATENTO AVISO⚠️ afectaciones tormenta inverna...,atento aviso afectacion tormenta invernal ciud...,[COP 25 sobre Cambio Climático],⚠️ATENTO AVISO⚠️ Debido a varias afectaciones ...,Negative,0.627384

In [38]:
print(sub_sample['Message'][646095])

⚠️ATENTO AVISO⚠️ Debido a varias afectaciones por la tormenta invernal en la ciudad de Tijuana, oficialmente se pospone la 4ta Manifestación Mundial por la Crisis Climática para el sábado 7 de Diciembre en el marco de la COP 25 sobre Cambio Climático. Ayudanos a compartir para que más personas se enteren. 🙏🌎

In [39]:
sub_sample[sub_sample['sentiment'] == 'Positive'].sort_values(by='score', ascending=False)

,Message,Message_stpWrd,Message_clean_lemm_stpWrd,organizations,Message_clean,sentiment,score
297546,Excelente iniciativa! Sumémosnos!,Excelente iniciativa! Sumémosnos!,excelente iniciativa sumemosno,[],Excelente iniciativa! Sumémosnos!,Positive,0.994401
256522,Una buena iniciativa. Felicitaciones a la @CAM...,iniciativa. Felicitaciones @CAMHUILA propuesta...,iniciativa felicitacion camhuila propuesta edu...,[@CAMHUILA],Una buena iniciativa. Felicitaciones a la @CAM...,Positive,0.994268
787423,"Que gran noticia, una cosa buenísima para el p...","noticia, cosa buenísima planeta",noticia cosa buenisimo planeta,[],"Que gran noticia, una cosa buenísima para el p...",Positive,0.992874
234216,¡Qué buena campaña! #PremiosEscobillaDeOro 10 ...,¡Qué campaña! #PremiosEscobillaDeOro 10 multin...,campana premiosescobilladeoro 10 multinacional...,[],¡Qué buena campaña! #PremiosEscobillaDeOro 10 ...,Positive,0.992004
1101783,"Hermosa iniciativa, gracias por educar a nuest...","Hermosa iniciativa, gracias educar niños.",hermoso iniciativa gracia educar nino,[],"Hermosa iniciativa, gracias por educar a nuest...",Positive,0.991898
...,...,...,...,...,...,...,...
329308,"Aumento de temperatura, incremento de niveles ...","Aumento temperatura, incremento niveles CO2 su...",aumento temperatura incremento nivel co2 subid...,[NASA],"Aumento de temperatura, incremento de niveles ...",Positive,0.345049
606307,Mañana a las 11:30 am no te puedes perder la e...,Mañana 11:30 am puedes perder entrevista harem...,manana 1130 am perder entrevista ivan lanegra ...,[],Mañana a las 11:30 am no te puedes perder la e...,Positive,0.342982
67766,Hay 3 cursos ebook de CEATECI para hacer negoc...,3 cursos ebook CEATECI negocios DAÑAR medio am...,3 curso ebook ceateci negocio danar medio ambi...,[TECNICOS],Hay 3 cursos ebook de CEATECI para hacer negoc...,Positive,0.342390
1267959,La alteración de temperaturas que se presentan...,alteración temperaturas presentan Sonora compo...,alteracion temperatura presentar sonoro compor...,[],La alteración de temperaturas que se presentan...,Positive,0.342380
878685,El Acuerdo de París establece cuotas nacionale...,Acuerdo París establece cuotas nacionales emis...,acuerdo paris establecer cuota nacional emisio...,[Acuerdo de París],El Acuerdo de París establece cuotas nacionale...,Positive,0.342102

In [40]:
sub_sample[sub_sample['sentiment'] == 'Negative'].sort_values(by='score', ascending=False)

,Message,Message_stpWrd,Message_clean_lemm_stpWrd,organizations,Message_clean,sentiment,score
666466,"“…Es peor de lo que uno imaginaba, es mucho pe...","“…Es peor imaginaba, peor”: Análisis efecto ca...",peor imaginar peor analisis efecto calentamien...,[],"“…Es peor de lo que uno imaginaba, es mucho pe...",Negative,0.983568
498761,"""Es un día triste para la comunidad global"": l...","""Es día triste comunidad global"": líderes inte...",dia triste comunidad global lider internaciona...,[Acuerdo de París],"""Es un día triste para la comunidad global"": l...",Negative,0.982469
785556,De mal en peor | ONU advierte sobre crisis med...,mal peor | ONU advierte crisis medioambiental ...,mal peor onu advertir crisis medioambiental mo...,[ONU],De mal en peor | ONU advierte sobre crisis med...,Negative,0.982309
252013,¡Que horror! Esto es culpa de obrador (sarcasmo).,¡Que horror! culpa obrador (sarcasmo).,horror culpa obrador sarcasmo,[],¡Que horror! Esto es culpa de obrador (sarcasmo).,Negative,0.981910
267935,Es un triste espectáculo ver el desprendimient...,triste espectáculo desprendimiento hielos mile...,triste espectaculo desprendimiento hielo milen...,[],Es un triste espectáculo ver el desprendimient...,Negative,0.981205
...,...,...,...,...,...,...,...
873358,#EventosVirtuales No te pierdas esta gran char...,"#EventosVirtuales pierdas charla virtual ""Camb...",eventosvirtual pierdar charla virtual cambio c...,[https://bit.ly/38dTxu4:=:https://www.agrosavi...,#EventosVirtuales No te pierdas esta gran char...,Negative,0.344494
307875,"No esperes más, preséntanos tu proyecto #clima...","esperes más, preséntanos proyecto #climatekic_...",esperser mas presentanos proyecto climatekicac...,[],"No esperes más, preséntanos tu proyecto #clima...",Negative,0.344328
1221067,"""No vemos que en la Ciudad estén haciendo algo...","""No vemos Ciudad protegernos cambio climático ...",ciudad proteger cambio climatico avecinar,[],"""No vemos que en la Ciudad estén haciendo algo...",Negative,0.342644
250982,Los árboles por sí solos no pueden salvarnos d...,árboles salvarnos cambio climático reforestaci...,arbol salvar cambio climatico reforestacion ay...,[],Los árboles por sí solos no pueden salvarnos d...,Negative,0.338550
1020482,Covid-19 no desaceleró el cambio climático: OM...,Covid-19 desaceleró cambio climático: OMM ➡️ h...,covid19 desacelero cambio climatico omm,[https://bit.ly/3nBS2jb:=:https://www.diariopr...,Covid-19 no desaceleró el cambio climático: OM...,Negative,0.337659

Now we need to extract each of the organizations alongside it's sentiment score. We will then loop through each, tallying up a total sentiment score and count.

Before we do that, we need to convert each value in the *organizations* column to a list.

In [41]:
# initialize sentiment dictionary
sentiment = {}

# loop through dataframe and extract org labels and sentiment scores into sentiment dictionary
for i, row in sub_sample.iterrows():
    # extract sentiment direction and score
    direction = row['sentiment']
    score = row['score']
    # loop through each label in organizations column
    for org in row['organizations']:
        # check if org label exists in sentiment dictionary already
        if org not in sentiment.keys():
            # if it doesn't, initialize new entry in dictionary
            sentiment[org] = {'Positive': [], 'Negative': [], 'Neutral': [],}
        # append positive/negative score to respective dictionary entry
        sentiment[org][direction].append(score)

In [42]:
sentiment['BOGOTÁ']

{'Positive': [0.6816926598548889,
  0.516435980796814,
  0.5245352387428284,
  0.5338535383343697,
  0.5480635017156601,
  0.5568593641122183,
  0.5665497779846191,
  0.5361912399530411,
  0.5423871815204621],
 'Negative': [],
 'Neutral': []}

Now we can loop through each organization entry in the sentiment dictionary and calculate an average positive, and average negative score:

**Question**: 
- *How can we include neutral sentiment?*

In [43]:
sentiment.keys()

dict_keys(['BOGOTÁ', 'Cambio Climático', 'RT', 'Parlamento británico', 'COP 25 sobre Cambio Climático', 'Comisión Ad Hoc', 'Comisiones Legislativas', 'ALIENTE', 'Alianza Energía y Territorio', 'Alianza Global Clima y Salud', 'Organización Mundial de la Salud', 'OMS', 'Razón', 'Unión de Pequeños Agricultores', 'Unión Europea', 'Radio Andalucía Información', 'CFE', 'PAN', 'MC', 'PRD', 'Senado de la República', 'PRI', 'Comisión Federal de Electricidad', 'International Surfing Association Surfrider Foundation Federación de Surf', 'Surfing Nation Magazine', 'AUSTRALIA', 'INCENDIOS', 'Sociedad Australiana de Animales', 'Universidad de Sydney', 'ACCIONA', 'Senior Policy Expert', 'European Desalination Society', 'Comité de Dirección de la', 'Fresh-Thoughts Consulting GmbH.', 'Estudios Internacional de Aqualia', 'La Federación Ambientalista Internacional', 'Comité de Dirección de Water Europe', 'Comisión Europea', 'Directiva', 'Wireless Innovative MMIC', 'OCDE', 'Comité Ejecutivo de Eureau', 'WIMMIC', 'ACNUR', 'Nasa', 'Secretario General de la ONU', 'Departamento de Geofísica', 'UNIVERSIDAD', 'Foro Económico Mundial', 'ps.3942', 'Pest Management Science', 'Fereres A. 2014', 'Journal of Photochemistry and Photobiology B: Biology 138:', 'Arthropod-Plant Interactions', 'Fereres A. 2013', 'ONU', 'IPCC', 'Nacionales @DiarioCoLatino Integrantes de la Mesa para la Gestión de Riesgos de El Salvador', 'Naciones Unidas', '🚜 https://www.lopezgarrido.com/trituradora-biomasa-tm-2000/?fbclid=IwAR214Jnb_y3B9pYVwvUpxsJbiRKKyF7NwiPOcncznCZM_9uRzVBNBeeVXrE', 'Ley de Cambio Climático', 'Oxfam', 'Secretaría de Medio Ambiente y Desarrollo Sustentable', 'Marina del Pilar', 'wwf.org.ec/planectate', 'DonatónBogotá', 'Mesa de Gobierno de la Convención Marco', 'Greenpeace', 'Grupo Intergubernamental de Expertos sobre el Cambio Climático', 'Médicos de Cádiz', 'CEOs', 'Objetivos de Desarrollo Sostenible', 'Universidad Complutense de Madrid', 'Consulta Gaceta UNAM', 'Gobierno', 'Reuters', 'Acuerdo de París', 'INECC', 'Cambio Climático y Políticas Públicas', 'WWF Paraguay', 'Titular', 'Oficina de Representación de Agricultura', 'Programa Nacional de Fertilizantes', 'Coordinadora del', 'CCI', 'Círculo de Derecho Administrativo', 'CDA', 'Asociación Civil Revista de Derecho Administrativo.', 'Banco de Crédito del Perú- BCP', 'Partido Acción Nacional', 'Reacciona por el Clima', 'Más', 'Cambio Climático y Desarrollo Territorial', 'Secretaría de Medio Ambiente', 'Skulls', 'IEBO', 'Comisión Estatal Forestal de Oaxaca', 'Instituto de la Juventud del Estado de Oaxaca', 'EFE', 'Orden del Día Primer Foto Nevando', 'Servicio Federal de Pesca y Vida Silvestre', 'Epson', 'Cambio Climático de la Asamblea Legislativa', 'PDC', 'GANA', 'PCN', 'Sol Central de la Galaxia', 'Instituto de Cambio Climático', 'Comisión de Recursos Naturales', 'Instituto del Cambio Climático BOLETÍN / CONGRESO CHILPANCINGO', 'Congreso', 'Ley de Cambio Climático del', 'Convención de las Naciones Unidas', 'GRO', 'Poder Ejecutivo', 'Instituto de Cambio Climático del Estado de Guerrero', 'CIA', 'Departamento de Defensa de Estados Unidos', 'Cambio Climatico', 'DANI', 'Sociedad', 'BCIE', 'Gobierno estadounidense', 'CAF', 'Banco de Desarrollo del Caribe', 'Banco Centroamericano de Integración Económica', 'Banco Interamericano de Desarrollo', 'Acuerdo Climático de París', 'Energía Renovable para América Latina y el Caribe', 'Banco de Desarrollo de América Latina', 'Cambio', 'DesarolloSostenible', 'Secretario Técnico de la Plataforma Boliviana Frente al Cambio Climático', '🦆 Especial #DiaMundialDeLosHumedales / Hace 25 años', 'WWF', 'Cascos verdes', 'Spotify', 'Results-based management', 'MATERIA DE GIRD A NIVEL INTERNACIONAL', 'Protección Civil', 'Gestión Integral de Riesgos de Desastre', 'GIRD A NIVEL NACIONAL E INTERNACIONAL', 'CARICOM', 'chains', 'World Wild Fund', 'UNESCO', '#plasticocean #unmundosinplastico #unmundosinresiduos #', 'Juntos', 'BID', 'Asamblea General de las Naciones Unidas Síguenos', 'Corporación Andina de Fomento', 'Alianza para el Desarrollo en Democracia', 'NeverStopExploring', '𝗔𝗣𝗢́𝗦𝗧𝗢𝗟𝗘𝗦', 'FAO', '#Naturaleza', 'Resolución A', 'Asamblea General', 'Asamblea General de las Naciones Unidas', 'MujeresEnCiencia', 'Sistema de Gestión de la Energía', 'Sistema de Gestión', 'ITSTE', 'ISO', 'ChileDice', 'Universidad de Washington Tacoma', 'Día Internacional contra el Cambio Climático', 'Fondo Verde', 'Grupo SADASI Yucatán', 'PP', 'SADASI', 'El Concejal', 'Unidad de Desarrollo Sustentable', 'Grupo SADASI', '🌐', 'Gerentes Regionales de Educación y Recursos Naturales', 'CREA', 'Embajada de Brasil', 'Foro Cambio Climático', 'Responsabilidad de Cristianos Iglesia Catedral de Fe', 'DONDE EXIGÍAN LA MODIFICACIÓN DE LAS', 'FECOMAN', 'CONVOCADA POR', 'EFECTO EL', 'MLA', 'Desarrollo Sostenible', 'Asamblea Legislativa', 'Comisión de Medio Ambiente', 'Oficina de Meteorología de Reino Unido para la Organización Meteorológica Mundial', 'OMM', 'UnidasPodemos', 'GIZ', 'GIZ Ecuador', 'HCU HafenCity Universität Hamburg', 'Cotopaxi IST COTOPAXI', 'Grupo FARO', 'IST Cotopaxi', 'Índice Metropolitano de la Calidad del Aire', 'Comisión Permanente de Ecología, Presidida', 'Porcelanosa', 'Castellón Información Iberdrola', 'Fiera', 'Los Angeles FC', 'Concacaf', 'http://tu.am/duqkJF', 'Shell', 'Ciencia Económica', 'Foro Internacional', 'PVEM', 'Sustentabilidad y el Desarrollo del Campo Mexicano', 'Cambio Climático - Unicach', 'UNICACH', 'Unicach Saludable', 'Filarmónica', 'Fundación para el Desarrollo', 'Grupo América', 'Secretaría de Educación de la Nación', 'Radio Brava', 'Universidad Nacional de Cuyo', 'Mendoza', 'Fondo Ítalo Peruano-FIP', 'Asociación Interétnica de Desarrollo de la Selva Peruana', 'Centro de Investigación para el Desarrollo Sustentable', 'Programa de las Naciones Unidas para el Desarrollo', 'Global Sustainable Tourism Council', 'Centro de Investigación', '\u2060', 'Amazonas #SwitchtoPlantBased #foodsystemchangenow #foodsystemchange #', 'Xunta', 'Site S.A.S.', 'VEOLIA', 'Día Internacional', 'Organización Mundial del Turismo–OMT', 'DíaMundialDelTurismo', 'las Naciones Unidas', 'BBC', 'MAS', 'Movimiento al Socialismo', 'Journal of Hydrology', 'AFP', 'ASPANION', 'Congreso de #Morelos Iniciativa', 'Empresaria y Ambientalista Cuernavacense', 'Hará Frente al Cambio Climático', 'Gestión Ambiental', 'Conselleria de Agricultura, Desarrollo Rural', 'Índice de Calidad del Aire', 'O3', 'NO2', 'Oficina para la Reducción del Riesgo de Desastres de la ONU', 'PROEZA', 'Subprocurador de Medio Ambiente', 'Procuraduría', 'PMA', 'Consejo Directivo y de Vigilancia', 'Investigaciones Desarrollo', 'Economía Ecológica', 'SOCIEDAD', 'Cambio Climático!', 'Bolivia Tv', 'The Nature Conservancy', 'Cruz Roja', 'WFP', 'World Wildlife Fund', 'Organización Mundial de Conservación', 'Fundación Vida', 'CDMX #Movilidad', 'Retweeted El Espectador', 'Popular', 'UCR', 'Foro ‘Micro-cuencas Quebrada de los Negritos', 'Federación de Estudiantes de la', 'Ciencias Sociales', 'Organización Black Waters', 'Comisión de Asuntos Ambientales', 'Integral', 'Academia Diwoo Siwoo.', 'Universidad Técnica de Berlín.', 'Escuela de Trabajo Social', 'CEMEX', 'CDP', 'COP20', 'Cambio Climático y Transporte del Centro Común de Investigación', 'Anthropocene Magazine', 'Unidad de Economía de la Energía', 'GV', 'Secretaria de Desarrollo Económico', 'Colectivo', 'Internacional', 'OTAN', 'UNFCCC', 'DW', 'Guajira-', 'G20', 'Científicos', 'Panel “Finance for the Mexican Climate Contributions', 'GTO', 'COP26', 'Carabineros', 'Comisión de Energía de la Cámara de España', 'CI', 'CUPOS', 'Wester Union', 'PRO Online', 'Permacultor-Permaculturer Research Institute', 'Fondo Verde para el Clima', 'Club Nueva Unión', '𝗨𝗡𝗜𝗢𝗡', 'Programa Club Ambiental', 'Deportivo Nueva Unión', 'Club Social', 'partido Morena', 'Tribunal Electoral del Estado de Guerrero', 'TEE-GRO', 'Comisión de Niñas', 'Tribunal Electoral del Poder Judicial de la Federación', 'Comisión de Niños', 'TEPJF', 'Comisiones de Educación Ciencia y Tecnología', 'Comisión de los Derechos de las Niñas', 'CSI', 'OIE', 'Confederación Sindical Internacional', 'Secretaría General de la Organización Internacional de los Empleadores', 'Reduce', 'Acción por el Clima.', 'UNICEF', 'México Evalúa', 'Foro de París', 'Grupo Montañero', 'UMH', 'UPM', 'Reducir', '#FridaysForFuture Jovenes', 'COP26 sobre Cambio Climático?', 'Telefónica', 'Gobierno Regional', 'Comité Regional sobre el Cambio Climático', 'Oficina para la Gestión del Riesgo y el Cambio Climático', 'Foro Internacional de Turismo', '#HazteCargoRepsol', 'PereiraEnVivoNoticias', 'Unidad Nacional para la Gestión del Riesgo de Desastres.', 'Corporación', 'Corporación Autónoma Regional de Risaralda', 'Guardia Nacional', 'Banco Mundial.', 'HACE 30 AÑOS', 'BOSQUES', 'United Nations University', '🛑¡Basta', 'POPULARMUNDO', 'USAID Digital Development Forum', 'Carbono Neutralidad', 'MIT', 'Sede del Senado', 'HOMOSEXUAL', 'Sociedad Argentina de Técnicos de la Caña de Azúcar', 'ARGENTINOS', 'MILLONES', 'Fondo Mundial del Medio Ambiente', 'GEF', 'Productores', 'NDC', 'Directora de Alianza MX?', 'Universidad de California', 'Alianza MX', 'Directora de University of California', '#RADIOACTIVACLIMA', 'Industria Automotriz', 'PROCESO', 'BlackRock', 'INF', 'Plan Veracruzano de Desarrollo', 'Cambio Climático del Congreso del Estado', 'FEMA', '𝗚𝗢𝗕𝗜𝗘𝗥𝗡𝗢', '🌑', 'Asamblea del Consejo', 'Centro de Políticas Educativas Federales', 'Consejo Federal de Educación', 'Sedronar', 'The Guardian', 'GUSTAVO PETRO', 'HUMANA', 'PETRO', "Foro Internacional Desertif'actions 2015", 'Movimiento Ciudadano', 'Senador de la República', 'Diputados', 'Sustentabilidad y Cambio Climático', 'Coordinación de Medio Ambiente', 'Comisión', 'Fox', 'UCI', 'Odebrecht', 'CONFIEP', 'Política de Acción Climática de Bogotá', 'APAZA', 'Asamblea Nacional', 'Fundaciones de Defensa de Medio Ambiente', 'Diputada', 'Embajador de la Union Europea', 'Bandera Azul Ecológica', 'Secretario General del PSE-EE', 'PNV', 'EH Bildu', 'https://asisucede.com.mx/se-une-toluca-al-fridays-for-future-piden-acciones-contra-cambio-climatico/', 'TIJUANA.-', 'Marina', 'Fomento de la Vida', 'Gerencia de Gestión Ambiental', 'Secretaría de Relaciones Exteriores', 'Pemex', 'Petróleos Mexicanos', 'Instituto Mexicano del Petróleo', 'Juventudes', 'LCOY', 'PELAGOS', 'Youth Climate', 'COP', 'Consejo de la Persona Joven', 'Fridays For Future Costa Rica', 'The Weather Channel', 'Investigadores', 'Universidad de Lakehead', 'DOLARES', 'Comunidad.', 'VALIOSO', '📃', 'REPSOL', 'FMI', 'Fondo de Resiliencia y Sostenibilidad', 'Fondo Monetario Internacional', 'Fondo.', 'Fondo', 'Servicio Ampliado', 'UK in Costa Rica', 'Siempre Integrando', 'Integrating EbA and NBS in public policy', 'Asociación Costa Rica', 'Gobierno de Bolsonaro', 'NOAA', 'Universidad Estatal de Ohio', 'BESOTES', 'Maestría de Políticas Públicas', 'Maestría de Economía Aplicada', 'UNA SOLA', 'UE', 'IMPLAN', 'LOS CABOS B.C.S. " Saber', 'Cosmos', 'Cambio Climático Interplanetario y las Profecías Extraterrestres', 'Conciencia Crística', 'PEDRO SÁNCHEZ', 'SPHN', 'Compañía', 'Defensor del Pueblo de Navarra', '🛑🦠💧', 'Acción', 'Servicio de Economía Circular', 'Fundación Sustrai Erakuntza', 'Ecologistas', 'REAS', 'Defensor del Pueblo de Nafarroa', '𝗗𝗲𝗻𝘂𝗻𝗰𝗶𝗮𝗻 𝗱𝗲𝗷𝗮𝗰𝗶𝗼́𝗻', 'Universidad', 'Marginaciones Sociales', 'Energías Sustentables, Transporte y Desarrollo.', 'UBA', 'Trabajo y Economía Social', 'Secretaría de Desarrollo Agropecuario', '¡Comprométete', 'ENGIE', 'Ejército', 'FRENTE A LA TEMPORADA', 'Oficina Nacional de Emergencia – Onemi', 'Armada', 'Corporación Chilena de la Madera – Corma y los Municipios', 'Fuerzas Armadas y de Orden', 'Policía de Investigaciones', 'Corporación Nacional Forestal - Conaf', 'Fundación por la Paz', 'Cámara Federal de Apelaciones', 'Comisión de Desarrollo Sustentable', 'DEFENSA DE LA NATURALEZA CONTRA', '✅ Enfoque', 'Sociedad Científica Estudiantil de Ingeniería Ambiental - UCB', 'RECAUDACIÓN', 'FIRMAS', 'FB', 'Secretaría de Desarrollo Urbano y Ecología', 'Vanderbilt University', 'new foundations to curb the progress of climate change', 'Asamblea Nacional de Gobiernos Regionales del Perú', 'TURÍSTICO A PUEBLO', 'Asociado Principal Carlos Padilla', 'Facultad de Jurisprudencia - URosario', 'MASIVO', 'Sociedad Mundial de Acuacultura Nuestro', 'Sociedad Mundial de Acuacultura', 'GOBIERNO', 'PRODUCTOS', 'WAS', 'Direcciones Municipales', 'Biodiversidad', 'Cuidades Costeras', 'SNAP', 'www.rionegro.gub.uy:=:https://www.rionegro.gub.uy/', 'California Institute of Technology', 'Caltech', 'Universidad de Puerto Rico-Río Piedras', 'Instituto Tecnológico de California', 'FAVOR DIFUNDIR', 'UPR', 'Fundación Nacional de Ciencias', 'VERANO PARA MAESTROS', 'Consejo Noruego para Refugiados', 'IFOAM Organics Europe', 'TPS', 'ONCE PAÍSES', 'ODNI', 'Departamento de Seguridad Nacional', 'Pentágono', 'Gobierno de Estados Unidos', 'BN', 'Asociación Internacional del Hidrógeno', 'IPHE', 'ASOLAN', 'Torneo Internacional de Robótica Educativa', 'Instituto Tecnológico de Estudios Superiores de Monterrey', 'Universidad Politécnica de Guanajuato', 'ROBONAU', 'Directora', 'Frost Dragon Subsistema', 'CONALEP', 'Secretaría de Educación de Guanajuato', 'Instituto Tecnológico de Monterrey', 'Instituto del BCP', '#IMPRESO', 'Iglesia', 'Asamblea de las Naciones Unidas', 'Departamento de Ecología de la Universidad Autónoma de Madrid', 'UAM Contacto', 'Institución', 'AYACUCHO', 'INIA', 'FSC', 'Director', 'WWF Internacional', 'ExigeLaVerdad', 'CENTA', 'COICA', 'Unicef', 'ApuntesConstituyentes', 'DIF Solidaridad', 'Blue Flag 88', '#Internacional', 'https://dca.gob.gt/noticias-guatemala-diario-centro-america/pais-recibe-atlas-para-frenar-cambio-climatico/', 'Cambio Climático y Desarrollo Rural', 'Transporte y Energía', 'Cooperación Financiera alemana', 'Carta de la Tierra', 'Directora del Plantel 19', 'FDRS', 'Cambio Climático - Idiger', 'Semana europea', 'MDS', 'Índice de Calidad de Vida', 'MADES', 'PNUD', 'BSC', 'ICV', 'Escuela de Agrónomos ETSIAM', 'Universidad de Córdoba', 'EMSO', 'Foro', 'Dirección de Protección al Medio Ambiente y Ecología', 'DONALD', 'Time', 'GRETA', 'RELÁJATE', 'Secretaría de Seguridad Ciudadana', 'AGENDADIARIA Hoy', 'DIRECTO', 'Diálogo', 'ESTAMOS', 'Asefa Seguros', 'Facultad de Economía de Ljubljana', 'proyecto Shishmaref', 'London College of Communication', 'The Sunday Times', 'FOTO8', 'Royal Photographic Society', 'GEO Germany', 'GEO France', 'La Repubblica', 'Wired UK', 'National Geographic', 'Asamblea General de la ONU', 'Desarrollo Económico, Finanzas', 'Comité', 'SEDARPA', 'Desarrollo Social', 'Universidad Veracruzana', 'Servicio Meteorológico Nacional', 'Harvard', 'Programa de Investigación de Cambio Global de Estados Unidos', 'Climate Institute', 'Academia Nacional de Ciencias Recomendó', 'CRECIMIENTO VERDE', 'BIODIVERSIDAD', 'Aporte de la Iglesia Por', 'Card', 'Monsanto', '#Tecnologia', 'Cámara de Diputados', 'LR', 'Secretaría Regional Ministerial de Agricultura', 'Dirección Cambio Climático Costa Rica', 'Radio Jaén', 'Cambio Climático: Volando hacia la Sostenibilidad.', 'Aviación Civil', 'Sembrando Vida', 'PRIMER PUNTO', 'QUE SE PONGA', 'FE', 'MORENA', 'POR FAVOR QUE ALGUIEN NOS AYUDE A CAMBIAR', 'LaNuevaEspiritualidad #', 'Global Environment Facility', 'Banco Mundial', 'CONAF', 'Servicio Agrícola y Ganadero', 'SAG', 'Alianza Mundial de los Suelos de la FAO UN', 'Secretaría de Ambiente y Cambio Climático', '🤔', 'Gobierno de la República', 'Birds Caribbean', 'Departamento de Recursos Naturales y', 'Reserva', 'El Espectador', 'The Wilson Center', 'EL PUEBLO', 'Partido Aprista Peruano', 'UN APRA', 'IZQUIERDA DEMOCRATICA', 'PSOE', 'El ISIS', 'Cofradía', 'heterodosso', 'NASA', 'Cambio Climático e Industrias Extractivas', 'Desarrollo Económico Sostenible', '¿Sabés', 'Petróleo', 'Canal Once', 'UACM', 'COP23', 'Climate Tracker', '#Estudio: El calentamiento global', 'ILUMINATI', 'TRUMP', 'Seminario Internacional: Ecología', 'Federación de Partidos Verdes de las Américas', 'Presidenta del Partido Verde de Bolivia', 'Foro de Innovación', 'Coordinador Económico en Cambio Climático', 'Energía y Medio Ambiente de Clapesuc', 'Conferencia Internacional sobre Cambio Climático', 'Organización de las Naciones Unidas', 'Movimiento Progresista', 'Secretaría de Medio Ambiente y', 'Comisión Medio Ambiente y', 'Studio', 'TBA21', 'Unidad de Edafología', 'ANA', 'SNRH', 'Pontificia Universidad Católica del Perú', 'RIBAGUA', 'Autoridad Nacional del Agua', 'Instituto Superior Técnico', 'Seguridad Nacional', 'Departamento de Defensa', 'Consejo de Seguridad Nacional', 'Urbaser', 'Pan American Silver', 'PanAmericanSilver', 'Unidades Mineras de Pan American Silver Perú', 'Oficialía de Partes del Congreso', 'Fracción', 'Frente', 'COP26 l PUEBLOS', 'Universidad Nacional', 'DíaInternacionalDeLaTierra', 'RecuperandoTuConfianza', 'Fridays for Future Marta Bordons', 'Foro Nacional en Gestión del Cambio Climático', 'Cambio Climático y Sustentabilidad', 'Comisión Legislativa de Protección Ambiental y Cambio Climático', 'Partido Verde Europeo', 'Federación Nacional de Cafeteros', 'Consejo de Estado', 'Entidad', 'Nestlé', 'HACER', 'PASA', 'QUE', 'Consejo de la Integración Social Centroamericana', 'Política Social del Gobierno de Bicentenario', 'https://bit.ly/2MZWoNS:=:https://lavozdelpueblo.com.ar/noticia/90434-%E2%80%9CSomos-la-%C3%BAltima-poblaci%C3%B3n-del-planeta-que-puede-parar-el-cambio-clim%C3%A1tico%E2%80%9D-', 'DIA INTERNACIONAL DE', 'WWF Bolivia', 'SNMPE', 'Serfor', 'Petróleo y Energía', 'Sociedad Nacional de Minería', 'Cooperación Alemana al Desarrollo', 'Consorcio de Investigación Económica y Social', 'Servicio Nacional Forestal y de Fauna Silvestre', 'Proyecto Plantaciones Forestales', 'APOSTANDO', '𝑪𝒐𝒄𝒉𝒂𝒃𝒂𝒎𝒃𝒂', '𝑬𝑵𝑪𝑼𝑬𝑵𝑻𝑹𝑶 𝑫𝑬 𝑱𝑼𝑽𝑬𝑵𝑻𝑼𝑫𝑬𝑺', '#Internacional 🕍El líder católico', 'ReservadeBiosfera #MinisteriodelMedioAmbiente Más', 'Dirección de Deportes y Juventud de la Secretaría de Gobierno', 'Florencia Dall´acqua', 'OMT', 'Acciona', 'Huawei', 'Asociación Peruana de Energías Renovables', 'Orange Energy Perú', 'TransiciónEnergética', 'On', 'IGNIS Energía', 'Cummins Inc', 'EDF', 'Fenix', 'Pontificia Universidad Católica de Chile', 'VIE', 'Vicerrectoría de Investigación y Extensión', 'Universidad Pedagógica', 'Asamblea Parlamentaria Euro-Latinoamericana', 'Parlamento Europeo', 'Directora de Responsabilidad Corporativa de L’Oréal', '#Transmisiónenvivo | MINAGRI | Viernes', '✅Más', 'Foro Político de Alto Nivel de las Naciones Unidas', 'Foro Urbano Mundial', 'Administración', 'Oficina de Relaciones Internacionales del Distrito', 'Desarrollo Económico', 'Centro de Ciencias de la Atmósfera UNAM', 'Comité Regional para el Ahorro Energético', 'TuBoleta.com Informes', 'Hoodwinked in the Hothouse', 'CambioClimático!', 'Comisión Nacional de Áreas Naturales Protegidas', 'Consejo Consultivo para el Desarrollo Sustentable', 'FOAG', 'CRS', 'Fondo de Agua y Agricultura', 'CONFORMAN', 'EMDESA', 'ACUGOLFO', 'FONDO DE AGUA', 'https://radio.uchile.cl/2021/08/25/que-es-el-cambio-climatico-curso-gratuito-online-y-para-todo-publico-de-la-u-de-chile-lo-explica/', 'Secretaría del Bienestar Sustentabilidad y Cambio Climático', 'United Nations', 'Foro ACT de Latinoamérica y Caribe', 'NA', 'ACT Alliance', 'Directora de CREAS', 'ACT', 'Junta de Gobierno de ACT Alianza', 'Foro ACT NA', 'Secretario Global', 'Foro ACT', 'Consejo de Iglesias', 'Servicio Nacional de Meteorología e Hidrología', 'Senador de Florida', 'Gobierno del Presidente', 'Fondo Integral de Desarrollo Agrícola', 'FIDA', 'URSS', 'CostaRica', 'Radio Nacional', 'Verdes', 'Asamblea General de las #', 'Servicio Geológico de Estados Unidos', 'Planes Reguladores', 'USGS', 'AyA.', 'Servicio Geológico de los Estados Unidos', 'SENARA', 'GENS', 'http://www.publico.es/economia/cambio-climatico-hara-23-mas.html:=:https://www.publico.es/economia/cambio-climatico-hara-23-mas.html', 'PNUMA', 'Representante', '✅ La Unión Europea', 'Cambio Climático! #YoReciclOrganicos ¿y tú?', 'AcuerdoDeParís', '#Em

In [44]:
# initialize sentiment list
avg_sentiment = []

# loop through each organization
for org in sentiment.keys():
    # get number of positive and negative ratings
    freq = len(sentiment[org]['Positive']) + len(sentiment[org]['Negative'])
    # Ommit organizations without Positives and Negatives Scores
    if freq == 0:
        continue
    for direction in ['Positive', 'Negative']:
        # assign to variable for cleaner code
        score = sentiment[org][direction]
        # if there are no entries, set to 0
        if len(score) == 0:
            sentiment[org][direction] = 0.0
        else:
            # otherwise calculate total
            sentiment[org][direction] = sum(score)
    # now calculate total amount
    total = sentiment[org]['Positive'] - sentiment[org]['Negative']
    # and the average score
    avg = total/freq
    # add to sentiment list
    avg_sentiment.append({
        'entity': org,
        'positive': sentiment[org]['Positive'],
        'negative': sentiment[org]['Negative'],
        'frequency': freq,
        'score': avg
    })

In [45]:
sentiment_df = pd.DataFrame(avg_sentiment)
sentiment_df.head()

                          entity     positive    negative  frequency     score
0                         BOGOTÁ     5.006568    0.000000          9  0.556285
1               Cambio Climático  1935.531332  683.173584       4087  0.306425
2                             RT     1.584514    4.136871         10 -0.255236
3           Parlamento británico     0.000000    3.646882          5 -0.729376
4  COP 25 sobre Cambio Climático     0.000000    0.627384          1 -0.627384

Immediately we can see we have a lot of entities which have appeared once in our dataset, and because of this their score will be pushed to one extreme or the other. We can filter out anything with less than or equal to a frequency of `100` to remove many of these instances:

In [46]:
sentiment_df = sentiment_df[sentiment_df['frequency'] > 100]
sentiment_df

,entity,positive,negative,frequency,score
1,Cambio Climático,1935.531332,683.173584,4087,0.306425
10,Organización Mundial de la Salud,46.357480,86.839093,211,-0.191856
11,OMS,74.693125,172.046119,381,-0.255520
14,Unión Europea,347.553320,158.944926,793,0.237842
16,CFE,29.022127,38.042800,109,-0.082758
...,...,...,...,...,...
2020,Ejecutivo,76.778078,45.911094,202,0.152807
2234,Medio Ambiente,60.525606,15.904163,121,0.368772
2242,Microsoft,37.436470,29.838657,107,0.071008
2306,CambioClimático,81.712578,54.719665,216,0.124967
2312,Universidad de Chile,56.422987,21.631779,124,0.280574

In [47]:
sentiment_df.head(30)

,entity,positive,negative,frequency,score
1,Cambio Climático,1935.531332,683.173584,4087,0.306425
10,Organización Mundial de la Salud,46.357480,86.839093,211,-0.191856
11,OMS,74.693125,172.046119,381,-0.255520
14,Unión Europea,347.553320,158.944926,793,0.237842
16,CFE,29.022127,38.042800,109,-0.082758
17,PAN,31.271277,43.184041,120,-0.099273
21,PRI,44.029428,54.355552,161,-0.064137
37,Comisión Europea,74.010832,29.714744,167,0.265246
55,ONU,880.045140,1023.803766,3010,-0.047760
56,IPCC,98.135061,278.140639,612,-0.294127
58,Naciones Unidas,413.198418,268.395646,1066,0.135837
60,Ley de Cambio Climático,48.609688,23.393887,124,0.203353
67,Greenpeace,54.658767,156.767208,337,-0.302992
68,Grupo Intergubernamental de Expertos sobre el ...,18.265744,69.726478,142,-0.362400
71,Objetivos de Desarrollo Sostenible,243.802664,28.019788,402,0.536773
74,Gobierno,271.536603,234.761637,812,0.045289
76,Acuerdo de París,155.776702,157.417863,519,-0.003162
91,Más,70.732481,28.844267,156,0.268514
92,Cambio Climático y Desarrollo Territorial,72.556167,18.017524,141,0.386799
93,Secretaría de Medio Ambiente,72.817345,14.148935,134,0.437824
98,EFE,25.027099,58.694775,133,-0.253140
110,Congreso,182.644004,162.571560,564,0.035589
126,Banco Interamericano de Desarrollo,80.777686,12.318196,143,0.478738
130,Cambio,66.823039,43.399105,169,0.138603
134,WWF,217.766925,77.118270,443,0.317491
145,UNESCO,107.733448,43.086376,222,0.291203
148,BID,56.990791,9.599233,103,0.460112
154,FAO,183.717858,111.814191,460,0.156312
157,Asamblea General,59.107653,23.672203,131,0.270500
158,Asamblea General de las Naciones Unidas,96.675463,26.974311,192,0.363027

# References

- [Hugging Face Bert](https://huggingface.co/docs/transformers/model_doc/bert)
- [Intro to Tokenizer for Bert](https://medium.com/@dhartidhami/understanding-bert-word-embeddings-7dc4d2ea54ca)
- [Hugging Face model DistilBert](https://huggingface.co/lxyuan/distilbert-base-multilingual-cased-sentiments-student?) 
- [Tokenizador de OpenAI](https://platform.openai.com/tokenizer)